branch-defaults:
  default:
    environment: udagram-api-dev
    group_suffix: null
environment-defaults:
  udagram-api-dev:
    branch: null
    repository: null
global:
  application_name: udagram-api
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
deploy:
  artifact: www/Archive.zip